import { defineConfig, env } from "prisma/config"
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"

export default defineConfig({
	schema: "prisma/schema.prisma",
	migrations: {
		path: "prisma/migrations",
	},
	// App requests: connect with DATABASE_URL, then SET LOCAL ROLE dentshift_app per request (see lib/db/with-dentist.ts).
	// Migrations use the same DATABASE_URL as superuser/bypass; run `npx prisma migrate deploy` before starting the app.
	datasource: {
		url: env("DATABASE_URL"),
	},
})
