import type { Metadata } from "next"
import HolyLoader from "holy-loader"
import { Sarabun } from "next/font/google"
import Layouts from "@/layouts"
import "@/styles/globals.css"

const sarabunSans = Sarabun({
	weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
	subsets: ["thai"],
	display: "swap",
})

export const metadata: Metadata = {
	title: "DentShift",
	manifest: "/manifest.json",
	description: "Generated by DentShift",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<HolyLoader color="#14b6c2" />
			<body
				className={`${sarabunSans.className} antialiased`}
				suppressHydrationWarning
			>
				<div id="portal"></div>
				<Layouts>{children}</Layouts>
			</body>
		</html>
	)
}
