import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import Layouts from "@/layouts"
import "@/styles/globals.css"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "DentShift",
	description: "Generated by DentShift",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				suppressHydrationWarning
			>
				<div id="portal"></div>
				<Layouts>{children}</Layouts>
			</body>
		</html>
	)
}
